import type { AnalysisResponse } from "@workspace/api-client-react";

export const SAMPLE_CONVERSATION = `Alex: I can't believe you forgot to pay the electric bill again.
Jordan: I didn't forget! I've just been completely swamped at work. You know how my boss has been breathing down my neck.
Alex: It's always an excuse. I feel like I have to manage everything in this house.
Jordan: That's not fair. I do the groceries and walk the dog every single morning. You always focus on the one thing I slip up on.
Alex: Because the electric bill is kind of important, Jordan! What if they shut off the power?
Jordan: They're not going to shut off the power after one missed day. You're overreacting and trying to make me feel like a child.
Alex: I'm just exhausted from carrying the mental load. 
Jordan: Well maybe if you were more supportive instead of constantly criticizing, I wouldn't be so stressed out in the first place.`;

export const FALLBACK_ANALYSIS: AnalysisResponse = {
  meta: {
    title: "Relationship Conflict Analysis",
    disclaimer: "This analysis is generated by AI and is intended for reflection, not clinical diagnosis. Tone and intent can be misinterpreted without full context.",
    savedRawText: false,
    redactionApplied: true,
    generatedAt: new Date().toISOString(),
  },
  input: {
    originalLength: 684,
    normalizedLength: 650,
    detectedSpeakers: ["Alex", "Jordan"],
    uncertainSpeakerAssignments: false,
  },
  parsedConversation: [
    { id: "1", speaker: "Alex", rawSpeaker: "Alex", text: "I can't believe you forgot to pay the electric bill again.", turn: 1, timestamp: null },
    { id: "2", speaker: "Jordan", rawSpeaker: "Jordan", text: "I didn't forget! I've just been completely swamped at work. You know how my boss has been breathing down my neck.", turn: 2, timestamp: null },
    { id: "3", speaker: "Alex", rawSpeaker: "Alex", text: "It's always an excuse. I feel like I have to manage everything in this house.", turn: 3, timestamp: null },
    { id: "4", speaker: "Jordan", rawSpeaker: "Jordan", text: "That's not fair. I do the groceries and walk the dog every single morning. You always focus on the one thing I slip up on.", turn: 4, timestamp: null },
    { id: "5", speaker: "Alex", rawSpeaker: "Alex", text: "Because the electric bill is kind of important, Jordan! What if they shut off the power?", turn: 5, timestamp: null },
    { id: "6", speaker: "Jordan", rawSpeaker: "Jordan", text: "They're not going to shut off the power after one missed day. You're overreacting and trying to make me feel like a child.", turn: 6, timestamp: null },
    { id: "7", speaker: "Alex", rawSpeaker: "Alex", text: "I'm just exhausted from carrying the mental load.", turn: 7, timestamp: null },
    { id: "8", speaker: "Jordan", rawSpeaker: "Jordan", text: "Well maybe if you were more supportive instead of constantly criticizing, I wouldn't be so stressed out in the first place.", turn: 8, timestamp: null },
  ],
  parties: [
    {
      id: "p1",
      name: "Alex",
      messageCount: 4,
      dominantStates: ["Frustrated", "Overwhelmed", "Critical"],
      stateConfidence: 88,
      notes: "Expresses feelings of exhaustion related to unequal distribution of responsibility ('mental load'). Uses absolute language ('always', 'everything') which escalates the conflict.",
    },
    {
      id: "p2",
      name: "Jordan",
      messageCount: 4,
      dominantStates: ["Defensive", "Stressed", "Invalidating"],
      stateConfidence: 92,
      notes: "Quickly shifts blame to external factors (boss) and later to Alex's behavior. Invalidates Alex's anxiety by labeling it as 'overreacting'.",
    }
  ],
  conversationSummary: "A domestic conflict regarding a missed utility payment escalates rapidly into a broader argument about the division of labor, mental load, and emotional support. The conversation exhibits a classic 'attack-defend' cycle where neither party feels heard.",
  toneScores: {
    authentic: 65,
    defensive: 85,
    supportive: 15,
    pressureSignals: 70,
    inconsistencySignals: 20,
  },
  patterns: [
    {
      label: "Defensive Deflection",
      description: "Responding to a complaint by introducing an external excuse rather than acknowledging the impact of the action.",
      branch: "Defensiveness",
      evidence: [
        { speaker: "Jordan", turn: 2, quote: "I've just been completely swamped at work. You know how my boss has been breathing down my neck." }
      ],
      confidence: 90,
      caution: "Context matters; the stress may be highly valid, but its use here functions to block accountability."
    },
    {
      label: "Absolute Generalization",
      description: "Using all-or-nothing words ('always', 'never') which often makes the recipient feel unfairly judged and triggers defensiveness.",
      branch: "Communication Blocking",
      evidence: [
        { speaker: "Alex", turn: 3, quote: "It's always an excuse. I feel like I have to manage everything in this house." },
        { speaker: "Jordan", turn: 4, quote: "You always focus on the one thing I slip up on." }
      ],
      confidence: 95,
      caution: "These words usually indicate high emotional distress rather than literal truth."
    },
    {
      label: "DARVO (Deny, Attack, Reverse Victim & Offender)",
      description: "A defensive reaction where the person confronted turns the accusation back on the person who brought it up.",
      branch: "Escalation",
      evidence: [
        { speaker: "Jordan", turn: 8, quote: "Well maybe if you were more supportive instead of constantly criticizing, I wouldn't be so stressed out in the first place." }
      ],
      confidence: 82,
      caution: "While a common defensive mechanism, it prevents resolving the original issue."
    }
  ],
  emotionalProgression: [
    { speaker: "Alex", turn: 1, state: "Accusatory", confidence: 85, rationale: "Direct confrontation about a failure to perform a task." },
    { speaker: "Jordan", turn: 2, state: "Defensive", confidence: 90, rationale: "Immediate denial followed by external justification." },
    { speaker: "Alex", turn: 3, state: "Resentful", confidence: 88, rationale: "Broadening the specific issue to a general pattern of unequal labor." },
    { speaker: "Jordan", turn: 6, state: "Dismissive", confidence: 85, rationale: "Minimizing the consequence and labeling the partner's reaction as excessive." },
    { speaker: "Alex", turn: 7, state: "Vulnerable", confidence: 75, rationale: "Dropping anger to state the underlying emotional truth (exhaustion)." },
    { speaker: "Jordan", turn: 8, state: "Retaliatory", confidence: 92, rationale: "Responding to vulnerability with a counter-attack regarding support." }
  ],
  replySuggestions: {
    gentle: "I know you're under a lot of pressure at work, and I appreciate the things you do around the house. When the bills get missed, I just feel panicked about the consequences.",
    assertive: "I hear that work is stressful right now. However, I need us to find a reliable system for these bills so I don't have to carry the worry of the power getting shut off.",
    boundaryFocused: "I'm not willing to argue about who does more. The issue right now is the electric bill. Let's figure out how to get it paid today, and we can discuss workload later.",
    deEscalating: "We're both stressed right now and this is turning into a bigger fight. Let's just get the bill paid online together right now, and take a breather.",
    pauseInstead: "I'm feeling too overwhelmed to talk about this productively right now. Give me 20 minutes to cool down, and then let's figure out the bill."
  },
  reflectionMessages: [
    {
      targetSpeaker: "Alex",
      message: "Consider noticing when you use words like 'always' or 'everything'. While your exhaustion is completely valid, absolute words tend to make the other person stop listening and start defending themselves."
    },
    {
      targetSpeaker: "Jordan",
      message: "When confronted with a mistake, try taking a breath before bringing up external stress. Acknowledging the missed task first ('You're right, I missed it') can completely diffuse the anger before you explain the 'why'."
    }
  ],
  safety: {
    confidenceNote: "Analysis is based strictly on linguistic markers. The model cannot know the true history of your relationship or external facts.",
    misusePrevention: [
      "Do not use this analysis to 'prove' you are right in an argument.",
      "Avoid showing these results to your partner as a weapon.",
      "If you feel unsafe in this relationship, please seek help from a licensed professional."
    ]
  }
};
